name: Build

on: push

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Compile LaTeX
      uses: dante-ev/latex-action@master
      with:
        root_file: cv-simon-albrecht.tex
        args: -pdf
    - name: Archive compiled PDF
      uses: actions/upload-artifact@v1
      with:
        name: cv
        path: cv-simon-albrecht.pdf